// <auto-generated />
using DataAccess.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AirportDbContext))]
    partial class AirportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Model.Airport", b =>
                {
                    b.Property<int>("AirportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AirportId"));

                    b.Property<int>("GeographyLevel1Id")
                        .HasColumnType("int");

                    b.Property<string>("IATACode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("AirportId");

                    b.HasIndex("GeographyLevel1Id");

                    b.ToTable("Airport");
                });

            modelBuilder.Entity("DataAccess.Model.AirportGroup", b =>
                {
                    b.Property<int>("AirportGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AirportGroupId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AirportGroupId");

                    b.ToTable("AirportGroup");
                });

            modelBuilder.Entity("DataAccess.Model.AirportsToAirportGroupsJoins", b =>
                {
                    b.Property<int>("AirportGroupId")
                        .HasColumnType("int");

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.HasKey("AirportGroupId", "AirportId");

                    b.HasIndex("AirportId");

                    b.ToTable("AirportsToAirportGroupsJoins");
                });

            modelBuilder.Entity("DataAccess.Model.Country", b =>
                {
                    b.Property<int>("GeographyLevel1Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeographyLevel1Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GeographyLevel1Id")
                        .HasName("Pk_GeographyLevel1Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("GeographyLevel1");
                });

            modelBuilder.Entity("DataAccess.Model.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<int>("ArrivalAirportGroupId")
                        .HasColumnType("int");

                    b.Property<int>("DepartureAirportGroupId")
                        .HasColumnType("int");

                    b.HasKey("RouteId");

                    b.ToTable("Route");
                });

            modelBuilder.Entity("DataAccess.Model.Airport", b =>
                {
                    b.HasOne("DataAccess.Model.Country", "Country")
                        .WithMany("Airports")
                        .HasForeignKey("GeographyLevel1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("DataAccess.Model.AirportsToAirportGroupsJoins", b =>
                {
                    b.HasOne("DataAccess.Model.AirportGroup", null)
                        .WithMany()
                        .HasForeignKey("AirportGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Model.Airport", null)
                        .WithMany()
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Model.Country", b =>
                {
                    b.Navigation("Airports");
                });
#pragma warning restore 612, 618
        }
    }
}
